import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
const hook=registerHooks({resolve(specifier,context,next){return next(context.parentURL?.includes('/src/')&&/^\.\/[\w-]+$/.test(specifier)?`${specifier}.ts`:specifier,context);}});
const {BANK_CAPACITY,newBank,bankValid,bankPlayerValid,bankItemValid,bankItems,bankDeposit,bankWithdraw}=await import('../src/bank.ts');
const {starterGear,GEAR}=await import('../src/progression.ts');
const {bagUsage}=await import('../src/bags.ts');hook.deregister();
const fresh=()=>({id:'hero',level:1,hp:100,maxHp:100,gold:123,appearance:{className:'Ranger'},...starterGear('Ranger'),inventory:{wood:12,crystal:0,herb:0,potion:0,relic:0},carriedItems:{'trail-bread':3},ownedBags:[],equippedBags:[null,null,null,null],auctions:[],bank:newBank()});
const item=(kind,id,quantity=1)=>({kind,id,quantity});
assert.equal(BANK_CAPACITY,48);assert(bankValid(newBank()));assert(bankPlayerValid(fresh()));
assert(bankPlayerValid({...fresh(),bank:undefined}),'legacy absence means an empty bank');
assert(!bankPlayerValid({...fresh(),bank:null}),'an explicitly null saved bank is malformed');
assert.equal(bankDeposit({...fresh(),bank:null},item('resource','wood')),null);
for(const invalid of [null,{},[],{...newBank(),gold:5},{...newBank(),resources:{wood:-1}},{...newBank(),resources:{wood:0}},{...newBank(),items:{unknown:1}},{...newBank(),gear:['not-a-gear']},{...newBank(),bags:[{id:'bad',kind:'linen-pouch'}]}])assert(!bankValid(invalid),'bank schema rejects invalid/unknown contents');
for(const invalid of [item('gold','gold',1),item('resource','wood',0),item('resource','wood',-2),item('resource','wood',1.1),item('resource','wood',1_000_001),item('resource','__proto__',1),{...item('resource','wood'),extra:1},item('bag','bad')])assert(!bankItemValid(invalid));
const player=fresh(),before=structuredClone(player),deposit=bankDeposit(player,item('resource','wood',5));
assert(deposit);assert.equal(deposit.inventory.wood,7);assert.equal(deposit.bank.resources.wood,5);assert.equal(deposit.gold,123);assert.deepEqual(player,before,'preparing a transfer never mutates the stored player');
const returned=bankWithdraw(deposit,item('resource','wood',2));assert.equal(returned.inventory.wood,9);assert.equal(returned.bank.resources.wood,3);assert.equal(deposit.bank.resources.wood,5);
assert.equal(bankDeposit(player,item('resource','wood',13)),null);assert.equal(bankWithdraw(player,item('resource','wood')),null);
const food=bankDeposit(player,item('item','trail-bread',3));assert(!Object.hasOwn(food.carriedItems,'trail-bread'));assert.equal(food.bank.items['trail-bread'],3);assert.equal(bankWithdraw(food,item('item','trail-bread',3)).carriedItems['trail-bread'],3);
assert.equal(bankDeposit(player,item('gear',player.equipment.weapon)),null,'equipped gear cannot leave the character');
const foreign=Object.values(GEAR).find(g=>g.className==='Mage'&&g.requiredLevel>1).id,found={...fresh(),ownedGear:[...player.ownedGear,foreign]};
const stored=bankDeposit(found,item('gear',foreign));assert(stored&&!stored.ownedGear.includes(foreign));assert(bankWithdraw(stored,item('gear',foreign)).ownedGear.includes(foreign),'returning owned gear is not a new class/level-gated purchase');
assert(!bankPlayerValid({...stored,ownedGear:[...stored.ownedGear,foreign]}),'gear cannot duplicate across bank and carried inventory');
assert(!bankPlayerValid({...stored,auctions:[{item:item('gear',foreign)}]}),'gear cannot duplicate across bank and auction escrow');
const bag={id:'11111111-1111-1111-1111-111111111111',kind:'linen-pouch'},withBag={...fresh(),ownedBags:[bag]};
const bagged=bankDeposit(withBag,item('bag',bag.id));assert(bagged);assert.equal(bagged.ownedBags.length,0);assert.deepEqual(bagged.bank.bags,[bag]);assert.deepEqual(bankWithdraw(bagged,item('bag',bag.id)).ownedBags,[bag]);
assert.equal(bankDeposit({...withBag,equippedBags:[bag.id,null,null,null]},item('bag',bag.id)),null,'equipped bags cannot change capacity through deposit');
assert(!bankPlayerValid({...bagged,ownedBags:[bag]}),'bag identity is unique across stores');
const fillers=Object.keys(GEAR).filter(id=>!player.ownedGear.includes(id)).slice(0,48),fullBank={...fresh(),bank:{...newBank(),gear:fillers.slice(0,47),resources:{wood:4}}};
assert.equal(bankItems(fullBank.bank).length,48);assert(bankDeposit(fullBank,item('resource','wood',1)),'an existing bank stack still accepts a deposit when every slot is occupied');
assert.equal(bankDeposit(fullBank,item('item','trail-bread',1)),null,'a new bank stack requires an empty slot');assert(!bankValid({...newBank(),gear:[...fillers,foreign]}),'overcapacity or duplicate bank gear is invalid');
const fullBags={...fresh(),ownedGear:[...player.ownedGear,...fillers.slice(0,14)],bank:{...newBank(),resources:{wood:3,crystal:2}}};
assert.equal(bagUsage(fullBags),16);assert(bankWithdraw(fullBags,item('resource','wood',3)),'existing carried stacks can merge at full bag capacity');assert.equal(bankWithdraw(fullBags,item('resource','crystal',2)),null,'a new carried stack cannot bypass capacity');
assert.equal(bankDeposit({...player,bank:{...newBank(),resources:{wood:Number.MAX_SAFE_INTEGER}}},item('resource','wood')),null,'bank stack arithmetic cannot overflow');
assert.equal(bankWithdraw({...player,inventory:{...player.inventory,wood:Number.MAX_SAFE_INTEGER},bank:{...newBank(),resources:{wood:1}}},item('resource','wood')),null,'carried stack arithmetic cannot overflow');
console.log('PASS bank: strict48-slot item storage, immutable projected transfers, partial stacks, capacity-safe merges, gear and bag identity, equipped exclusions, own-gear returns, overflow rejection and no gold transfer.');
