import type { EnemyKind } from './bestiary.ts';
import { GEAR_QUALITIES, type GearQuality } from './progression.ts';

export type PetLootQuality = GearQuality;
export const PET_LOOT_QUALITIES = GEAR_QUALITIES;
export const PET_LOOT_RADIUS = 12;

export const PETS = [
  { id: 'death-apostle', name: 'Death Apostle', description: 'A four-armed shadow companion earned from the Horned Apostle raid. Evolve it with raid cores and an Apostle’s Soul.', source: null, dropChance: 0, icon: '/ui/pets/death-apostle.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'bramble-badger', name: 'Bramble Badger', description: 'A striped woodland badger with slate fur, a leafy bramble mantle and tiny ruby berries.', source: 'bramble-wolf', dropChance: .00025, icon: '/ui/pets/bramble-badger.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'duskwind-raven', name: 'Duskwind Raven', description: 'A midnight raven with layered violet feathers, a silver beak and sweeping dusk-blue wings.', source: 'briar-sentinel', dropChance: .00025, icon: '/ui/pets/duskwind-raven.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'ember-axolotl', name: 'Ember Axolotl', description: 'A cheerful axolotl with glowing coral gills, molten freckles and a broad ember-tipped tail.', source: 'ember-beetle', dropChance: .00025, icon: '/ui/pets/ember-axolotl.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'geode-hedgehog', name: 'Geode Hedgehog', description: 'A round little hedgehog with teal and emerald crystal spines, icy silver tips and a curious pointed nose.', source: 'stone-golem', dropChance: .00025, icon: '/ui/pets/geode-hedgehog.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'clover-mouse', name: 'Clover Mouse', description: 'A tiny field mouse with round pink ears, a leafy clover cap and a long curling tail.', source: 'moss-slime', dropChance: .00025, icon: '/ui/pets/clover-mouse.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'dewbell-dragonfly', name: 'Dewbell Dragonfly', description: 'A delicate dragonfly with four pale, etched leaf wings, turquoise eyes and an icy dewdrop bell.', source: 'grove-spider', dropChance: .00025, icon: '/ui/pets/dewbell-dragonfly.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'snowcap-stoat', name: 'Snowcap Stoat', description: 'A slender white stoat with a snow-dusted teal mushroom cap, soft pink ears and a dark-tipped winter tail.', source: 'frost-yeti', dropChance: .00025, icon: '/ui/pets/snowcap-stoat.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'suncrest-peacock', name: 'Suncrest Peacock', description: 'A radiant peacock with a golden crest, teal neck and a fan of jeweled sunlit feathers. Found only on the level 40 Ashen Crown Titan world boss.', source: 'ashen-crown-titan', dropChance: .00025, icon: '/ui/pets/suncrest-peacock.png', quality: 'epic', storeOnly: false, retired: false },
  { id: 'fern-lynx', name: 'Fern Lynx', description: 'A tuft-eared woodland lynx with layered fern fur, spotted flanks and a braided vine collar.', source: null, dropChance: 0, icon: '/ui/pets/fern-lynx.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'moonveil-gryphlet', name: 'Moonveil Gryphlet', description: 'A moonlit gryphon fledgling with layered flight feathers, a silver crest and tiny golden talons.', source: null, dropChance: 0, icon: '/ui/pets/moonveil-gryphlet.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'cinder-salamander', name: 'Cinder Salamander', description: 'A bright-eyed salamander with overlapping ember scales, charcoal dorsal fins and a glowing tail.', source: null, dropChance: 0, icon: '/ui/pets/cinder-salamander.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'amethyst-terrapin', name: 'Amethyst Terrapin', description: 'An ancient little terrapin with teal scales, silver-edged shell plates and clustered amethyst crystals.', source: null, dropChance: 0, icon: '/ui/pets/amethyst-terrapin.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'blossom-jackalope', name: 'Blossom Jackalope', description: 'A long-eared jackalope with branching antlers, layered blossom petals and a soft leafy ruff.', source: null, dropChance: 0, icon: '/ui/pets/blossom-jackalope.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'lantern-sprite', name: 'Lantern Sprite', description: 'A woodland sprite with veined leaf wings, an acorn cowl and a glowing abdomen cradled in a golden cage.', source: null, dropChance: 0, icon: '/ui/pets/lantern-sprite.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'rime-red-panda', name: 'Rime Red Panda', description: 'A frost-dusted red panda with a striped plume tail, fluffy cheek ruffs and tiny crystalline ornaments.', source: null, dropChance: 0, icon: '/ui/pets/rime-red-panda.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'crown-pangolin', name: 'Crown Pangolin', description: 'A regal pangolin with overlapping gilded scales, jeweled armor and a crown of polished brass. A retired drop once found on the level 40 Ashen Crown Titan world boss.', source: null, dropChance: 0, icon: '/ui/pets/crown-pangolin.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'moss-fox', name: 'Moss Fox', description: 'A woodland fox with fern-tipped ears and a lush mossy tail.', source: null, dropChance: 0, icon: '/ui/pets/moss-fox.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'moon-owl', name: 'Moon Owl', description: 'A silver-feathered owl with a crescent crown and luminous eyes.', source: null, dropChance: 0, icon: '/ui/pets/moon-owl.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'ember-drake', name: 'Ember Drake', description: 'A tiny dragon with layered scales, glowing embers and copper wings.', source: null, dropChance: 0, icon: '/ui/pets/ember-drake.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'crystal-tortoise', name: 'Crystal Tortoise', description: 'A patient companion carrying a garden of brilliant crystals on its shell.', source: null, dropChance: 0, icon: '/ui/pets/crystal-tortoise.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'bloom-hare', name: 'Bloom Hare', description: 'A soft forest hare adorned with tiny flowers and curling leaves.', source: null, dropChance: 0, icon: '/ui/pets/bloom-hare.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'lantern-moth', name: 'Lantern Moth', description: 'An ornate moth whose patterned wings cradle a warm lantern glow.', source: null, dropChance: 0, icon: '/ui/pets/lantern-moth.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'frost-cub', name: 'Frost Cub', description: 'A snowy bear cub with frost-tipped fur and sparkling ice ornaments.', source: null, dropChance: 0, icon: '/ui/pets/frost-cub.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'golden-pig', name: 'Golden Pig', description: 'A gilded little pig with a jeweled crown, filigree armor and a curly golden tail. A retired drop once found on the level 40 Ashen Crown Titan world boss.', source: null, dropChance: 0, icon: '/ui/pets/golden-pig.png', quality: 'epic', storeOnly: false, retired: true },
  { id: 'store-ashwing', name: 'Ashwing', description: 'An obsidian drake with a molten crown, ember scales and broad wings of living fire.', source: null, dropChance: 0, icon: '/ui/pets/store-ashwing.png', quality: 'epic', storeOnly: true, retired: false },
  { id: 'store-cinder-kit', name: 'Cinder Kit', description: 'A bright-eyed fox with two flowing ember tails and a tiny golden flame collar.', source: null, dropChance: 0, icon: '/ui/pets/store-cinder-kit.png', quality: 'epic', storeOnly: true, retired: false },
  { id: 'wayfinder-sprite', name: 'Wayfinder Sprite', description: 'A little woodland guide with jade leaf wings, an acorn crown and a golden compass lantern. Earned by referring ten qualified adventurers; shared by your account and never traded.', source: null, dropChance: 0, icon: '/ui/pets/wayfinder-sprite.png', quality: 'epic', storeOnly: false, retired: false, referralOnly: true },
] as const satisfies readonly { id: string; name: string; description: string; source: EnemyKind | null; dropChance: number; icon: string; quality: 'epic'; storeOnly: boolean; retired: boolean; referralOnly?: boolean }[];

export type PetId = typeof PETS[number]['id'];
export const petById = (id: unknown) => PETS.find(pet => pet.id === id);
export const isPetId = (id: unknown): id is PetId => petById(id) !== undefined;
