import type { ClientMessage, Player } from './shared';
import { newRaidProgress, RAID_COSMETICS, RAID_REWARD_TABLE, SPECIALIST_NAMES, SPECIALISTS_ENABLED, SP_UPGRADE_ODDS, specialistJobLevel, specialistUpgradeCost, type RaidCosmetic } from './raid-progression';
import { icon } from './icons';

const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(label:string,action:string,disabled=false,extra='')=>`<button type="button" class="primary-button" data-raid-progression="${action}" ${extra} ${disabled?'disabled':''}>${label}</button>`;
export function renderRaidProgression(player:Player):string {
 const progress=player.raidProgress||newRaidProgress(),eligible=player.level>=60,canUnlock=eligible&&(progress.clears>0||!!player.achievements?.dungeons.veilhaven)&&!progress.claimedSpecialistClasses?.includes(player.appearance.className)&&!progress.specialists.some(card=>card.source==='quest'&&card.className===player.appearance.className);
 const items=player.carriedItems||{},ownsPet=player.ownedPets.includes('death-apostle'),coresNeeded=[1,3,6][progress.petEvolution]??0;
 const cosmeticArt:Record<RaidCosmetic,string>={'apostle-wings':'wings','black-aura':'aura','apostle-weapon':'weapon'};
 const cosmeticCount=RAID_COSMETICS.filter(id=>progress.cosmetics.includes(id)).length;
 return `<section class="raid-panel raid-progression"><header class="raid-panel-heading"><h3>Raid collection</h3><strong>${progress.clears} clears</strong></header><dl class="raid-materials"><div><dt>Raid Sigils</dt><dd>${progress.sigils}</dd></div><div><dt>Apostle’s Souls</dt><dd>${progress.souls}</dd></div><div><dt>Evolution Cores</dt><dd>${progress.evolutionCores}</dd></div></dl>${progress.pendingHorns?button('Collect Death Horns','horns',!eligible):''}
 <h3 class="raid-collection-heading">Apostle cosmetics <small>${cosmeticCount} / ${RAID_COSMETICS.length} collected</small></h3><div class="raid-rewards raid-cosmetic-cards">${RAID_COSMETICS.map(id=>{const owned=progress.cosmetics.includes(id),equipped=progress.equippedCosmetics.includes(id),reward=RAID_REWARD_TABLE.find(item=>item.id===id)!;return `<article class="${owned?'is-collected':'is-missing'}"><img src="/ui/raid/${cosmeticArt[id]}.png" alt="" width="88" height="88"><strong>${reward.label}</strong><span class="raid-collection-state">${equipped?'Equipped':owned?'Collected':'Not collected'}</span><small>${reward.chance*100}% personal chance per raid clear</small>${button(owned?equipped?'Unequip':'Equip':'Not collected','cosmetic',!eligible||!owned,`data-cosmetic="${id}" data-equipped="${!equipped}"`)}</article>`;}).join('')}</div>
 <h3 class="raid-collection-heading">Death Apostle pet <small>Evolution ${progress.petEvolution} / 3</small></h3><section class="raid-pet-evolution"><img src="/ui/pets/death-apostle.png" alt="Death Apostle companion" width="104" height="104"><div><strong>${ownsPet?'Evolve your companion':'Not collected'}</strong><ol class="raid-evolution-steps" aria-label="Evolution stages">${[1,2,3].map(stage=>`<li class="${stage<=progress.petEvolution?'is-complete':''}" aria-label="Stage ${stage}${stage<=progress.petEvolution?' complete':''}">${stage<=progress.petEvolution?'✓':stage}</li>`).join('')}</ol><p>${ownsPet?progress.petEvolution===3?'Fully evolved. Your companion has reached its final appearance.':`Next evolution: ${coresNeeded} cores${progress.petEvolution===2?' + 1 Apostle’s Soul':''}. Changes your companion’s appearance.`:'Defeat the Apostle for a chance to collect this companion.'}</p>${ownsPet&&progress.petEvolution<3?`<label class="raid-evolution-progress">Evolution Cores: ${progress.evolutionCores} / ${coresNeeded}<progress max="${coresNeeded}" value="${Math.min(coresNeeded,progress.evolutionCores)}">${progress.evolutionCores} / ${coresNeeded}</progress></label>${progress.petEvolution===2?`<p>Apostle’s Souls: ${progress.souls} / 1</p>`:''}${button('Evolve companion','evolve',!eligible||progress.evolutionCores<coresNeeded||progress.petEvolution===2&&!progress.souls)}`:''}</div></section>
 <h3>${icon('menu-specialist')} Specialists</h3><p>${SPECIALISTS_ENABLED?'Earn your class specialist by clearing Veilhaven or the raid at level 60. Equipped specialists earn job XP from XP-awarding activities. Upgrade power: +2 per rank; defense: +1 per three ranks. Wings appear at +5, +10 and +15.':'Specialist classes are temporarily disabled. Cards, upgrades and saved Job XP are preserved. You can manage and trade cards, but they grant no combat bonuses, Job XP or specialist wings.'}</p>${button('Claim class specialist +0','unlock',!canUnlock)}
 <div class="raid-specialists">${progress.specialists.map(card=>{
  const available=eligible&&!card.sealed&&card.className===player.appearance.className,active=SPECIALISTS_ENABLED&&progress.activeSpecialistId===card.id,odds=SP_UPGRADE_ODDS[card.upgrade],cost=specialistUpgradeCost(card.upgrade),attrs=`data-specialist-id="${escape(card.id)}"`,materials=player.inventory.crystal>=cost.crystal&&player.inventory.relic>=cost.relic&&progress.sigils>=cost.sigils;
  return `<article class="raid-specialist"><h4>${SPECIALIST_NAMES[card.className]} +${card.upgrade}</h4><p>${card.className} · Job ${specialistJobLevel(card.jobXp)} / 20 · ${card.jobXp.toLocaleString()} XP${card.sealed?' · Sealed for NFT trading':card.broken?' · Fractured':active?' · Equipped':''}</p>${button(!SPECIALISTS_ENABLED?'SP disabled':active?'Unequip':'Equip','equip',!SPECIALISTS_ENABLED||!available||card.broken,`${attrs} data-equipped="${!active}"`)}${card.broken?button('Repair · 1 Revival Core','repair',!available||!items['sp-revival-core'],attrs):odds&&!card.sealed?`<p>+${card.upgrade+1}: ${odds[0]}% success · ${odds[1]}% fracture · ${100-odds[0]-odds[1]}% unchanged.</p><p>${cost.crystal} crystal${cost.relic?` · ${cost.relic} relic`:''}${cost.sigils?` · ${cost.sigils} sigils`:''}. Materials are consumed on every attempt.</p><div class="raid-actions">${button(`Try +${card.upgrade+1}`,'upgrade',!available||!materials,`${attrs} data-upgrade="${card.upgrade}" data-attempts="${card.attempts}" data-protect="false"`)}${odds[1]?button(`Protect +${card.upgrade+1} · 1 Roll`,'upgrade',!available||!materials||!items['sp-protection-roll'],`${attrs} data-upgrade="${card.upgrade}" data-attempts="${card.attempts}" data-protect="true"`):''}</div>`:''}</article>`;
 }).join('')||'<p>No specialists collected.</p>'}</div><p>Protection Rolls prevent fractures without increasing success. Fractured specialists keep all levels. Buy Protection Rolls, Revival Cores and Specialist Cases in the MOSS store, or trade unused items for gold at the Auction House.</p><p>${items['sp-protection-roll']||0} Protection Rolls · ${items['sp-revival-core']||0} Revival Cores · ${items['sp-specialist-case']||0} Specialist Cases</p>
 <details class="raid-guide"><summary>Raid reward chances</summary><dl class="raid-reward-odds">${RAID_REWARD_TABLE.map(item=>`<div><dt>${item.label}</dt><dd>${item.chance*100}%${item.id==='raid-sigil'?' · 3–5 per clear':''}</dd></div>`).join('')}</dl><p>Each reward rolls independently. Duplicate cosmetics, pets and horns become two Sigils. Death Defier unlocks on your first clear.</p></details></section>`;
}
export function raidProgressionAction(data:DOMStringMap):ClientMessage|null {
 switch(data.raidProgression){
  case 'unlock':return {type:'raidSpUnlock'};
  case 'horns':return {type:'raidClaimHorns'};
  case 'evolve':return {type:'raidPetEvolve'};
  case 'equip':return {type:'raidSpEquip',specialistId:data.equipped==='true'?data.specialistId||null:null};
  case 'repair':return {type:'raidSpRepair',specialistId:data.specialistId||''};
  case 'upgrade':return {type:'raidSpUpgrade',specialistId:data.specialistId||'',protect:data.protect==='true',expectedUpgrade:Number(data.upgrade),expectedAttempts:Number(data.attempts)};
  case 'cosmetic':return {type:'raidCosmeticEquip',cosmetic:data.cosmetic as RaidCosmetic,equipped:data.equipped==='true'};
  default:return null;
 }
}
