import { SPELL_EFFECT_IDS, type AbilityId, type SpellArtId } from './spells.ts';

export type SpellMotif = 'flame' | 'shard' | 'spark' | 'rune' | 'leaf' | 'feather' | 'shield' | 'slash' | 'ring' | 'arrow';
export interface SpellVisual { motif: SpellMotif; color: string; accent: string; tones?: readonly [string, string, string, string] }

const bow = ['#dfb56e', '#fff5ce'] as const, nature = ['#74c984', '#e8ffd0'] as const;
const venom = ['#95d848', '#e2ff95'] as const, steel = ['#c0d7e7', '#fff1ba'] as const;
const earth = ['#d69f60', '#ffde9a'] as const, fire = ['#ff763a', '#fff1aa'] as const;
const frost = ['#75d8fa', '#edffff'] as const, arcane = ['#b894ff', '#e8d8ff'] as const;
const holy = ['#f9cf77', '#fffde0'] as const, healing = ['#abebcc', '#fff9d5'] as const;
// Bark, moss, jade and bone match the wild companions and Verdant Revenant materials.
const woodland = ['#554235', '#528364', '#8cc8ad', '#d9d5a0'] as const;
const v = (motif: SpellMotif, [color, accent]: readonly [string, string], tones?: SpellVisual['tones']): SpellVisual => ({ motif, color, accent, ...(tones ? { tones } : {}) });

/** Explicit aliases only; reworked spells each have their own authored sequence. */
export const SPELL_CHOREOGRAPHY_SOURCES: Partial<Record<SpellArtId, SpellArtId>> = {};

// Palette and the minimal crowded-combat cue. Individual choreography lives in spell-art-*.ts.
export const SPELL_VISUALS: Record<SpellArtId, SpellVisual> = {
  [SPELL_EFFECT_IDS.revivify]: v('ring', healing),
  [SPELL_EFFECT_IDS.roll]: v('feather', nature),
  [SPELL_EFFECT_IDS.blink]: v('rune', arcane),
  [SPELL_EFFECT_IDS.lightspeed]: v('feather', holy),
  'edict-of-the-dawn': v('ring', healing),
  'titans-edict': v('shield', holy),
  'eternal-edict': v('rune', holy),
  // Ranger: fletching, brambles and venom; a precise bow contrasts with a broad arrow rain.
  arrow: v('arrow', bow),
  'hamstring-shot': v('arrow', bow),
  'power-shot': v('arrow', bow),
  'trail-mending': v('leaf', nature),
  'poison-shot': v('arrow', venom),
  'concussive-shot': v('arrow', bow),
  multishot: v('arrow', bow),
  barkskin: v('leaf', nature),
  volley: v('arrow', bow),
  'frost-arrow': v('arrow', frost),
  'ricochet-shot': v('arrow', bow),
  'hunters-reprieve': v('feather', nature),
  'piercing-shot': v('arrow', steel),
  thornburst: v('leaf', nature),
  'serpent-fan': v('arrow', venom),
  'rapid-fire': v('arrow', bow),
  'explosive-arrow': v('arrow', fire),
  'silken-guard': v('ring', nature),
  'tranquilizing-shot': v('feather', nature),
  'wild-renewal': v('leaf', nature),
  'razor-flurry': v('slash', steel),
  'viper-strike': v('arrow', venom),
  'forest-ward': v('leaf', nature),
  'hail-of-arrows': v('arrow', bow),
  'binding-arrow': v('leaf', nature),
  'eagles-eye': v('feather', bow),
  'frostfall-volley': v('arrow', frost),
  'survival-instinct': v('leaf', nature),
  'starfall-arrow': v('arrow', arcane),
  'relentless-volley': v('arrow', bow),
  'heart-of-the-wild': v('leaf', nature),
  'tame-beast': v('leaf', nature),
  'combined-assault': v('slash', steel),
  twinshot: v('arrow', bow),
  'venom-detonation': v('leaf', venom),
  'poison-cloud': v('leaf', ['#7d8a46', '#b8d483'], woodland),

  // Knight: readable blade arcs, hammered shields, and rising fractures in the ground.
  strike: v('slash', steel),
  'crippling-strike': v('slash', steel),
  cleave: v('slash', steel),
  'second-wind': v('ring', healing),
  'shield-bash': v('shield', steel),
  'iron-guard': v('shield', steel),
  whirlwind: v('slash', steel),
  'heavy-slash': v('slash', steel),
  shockwave: v('ring', earth),
  'shield-toss': v('shield', steel),
  'rallying-cry': v('ring', healing),
  'concussive-blow': v('slash', steel),
  'steel-bulwark': v('shield', steel),
  groundbreaker: v('shard', earth),
  'crushing-sweep': v('slash', earth),
  bladestorm: v('slash', steel),
  'quick-recovery': v('spark', healing),
  'shattering-throw': v('slash', steel),
  earthshaker: v('shard', earth),
  'guardian-oath': v('shield', steel),
  'relentless-strike': v('slash', steel),
  'defiant-stand': v('ring', healing),
  chainbreaker: v('slash', steel),
  fortress: v('shield', steel),
  thunderclap: v('spark', steel),
  'colossus-strike': v('slash', earth),
  'stalwart-company': v('shield', steel),
  siegebreaker: v('shard', earth),
  'unyielding-blows': v('slash', steel),
  'battle-renewal': v('spark', healing),
  'last-bastion': v('shield', steel),
  charge: v('slash', ['#6e7a80', '#b9954c'], woodland),
  taunt: v('leaf', ['#528364', '#cbb087'], woodland),
  'powerful-throw': v('shield', ['#956543', '#b9954c'], woodland),
  guard: v('shield', ['#79613c', '#83b670'], woodland),
  'adamant-guardian': v('shield', ['#6e7a80', '#8cc8ad'], woodland),
  'courageous-call': v('feather', ['#a88949', '#d9d5a0'], woodland),
  'lord-of-battle': v('leaf', ['#79613c', '#91bc80'], woodland),

  // Mage: turbulent flame, faceted frost and precisely orbiting arcane geometry.
  fireball: v('flame', fire),
  'arcane-missile': v('rune', arcane),
  frostbolt: v('shard', frost),
  'flame-barrier': v('flame', fire),
  nova: v('shard', frost),
  'ice-lance': v('shard', frost),
  'arcane-burst': v('rune', arcane),
  cinderbolt: v('flame', fire),
  meteor: v('flame', fire),
  'arcane-restoration': v('rune', arcane),
  'frozen-orb': v('shard', frost),
  spellward: v('rune', arcane),
  pyroblast: v('flame', fire),
  'arcane-barrage': v('rune', arcane),
  'deep-freeze': v('shard', frost),
  'arcane-beam': v('rune', arcane),
  'ice-barrier': v('shard', frost),
  flamewave: v('flame', fire),
  blizzard: v('shard', frost),
  'ley-renewal': v('rune', arcane),
  'glacial-spike': v('shard', frost),
  'comet-shower': v('shard', frost),
  'prismatic-guard': v('shard', arcane),
  'chain-lightning': v('spark', arcane),
  'flash-freeze': v('shard', frost),
  'inferno-beam': v('flame', fire),
  blinkward: v('rune', arcane),
  starfire: v('spark', arcane),
  winterstorm: v('shard', frost),
  'arcane-tempest': v('rune', arcane),
  'aegis-of-the-archmage': v('rune', arcane),
  'arcane-volley': v('rune', arcane),
  combustion: v('flame', fire),
  shatter: v('shard', frost),

  // Cleric: feathered light and inscribed halos; healing opens upward, judgment strikes down.
  smite: v('spark', holy),
  heal: v('feather', healing),
  'holy-nova': v('ring', holy),
  'flash-heal': v('feather', healing),
  'power-word-shield': v('shield', holy),
  renew: v('feather', healing),
  'searing-light': v('spark', holy),
  'binding-light': v('ring', holy),
  'prayer-of-healing': v('feather', healing),
  'holy-fire': v('flame', holy),
  penance: v('rune', holy),
  'holy-word-serenity': v('rune', healing),
  'divine-aegis': v('shield', holy),
  'chains-of-light': v('ring', holy),
  'circle-of-healing': v('ring', healing),
  'divine-hymn': v('feather', healing),
  'radiant-burst': v('spark', holy),
  'guardian-light': v('feather', holy),
  'greater-heal': v('feather', healing),
  'sacred-flame': v('flame', holy),
  'prayer-of-mending': v('feather', healing),
  'holy-word-chastise': v('rune', holy),
  sanctuary: v('ring', holy),
  judgment: v('rune', holy),
  salvation: v('feather', healing),
  'holy-lance': v('arrow', holy),
  'seraphic-barrier': v('feather', holy),
  'cleansing-radiance': v('ring', holy),
  'light-of-dawn': v('feather', healing),
  'wrath-of-heaven': v('rune', holy),
  'guardian-of-the-dawn': v('feather', holy),
};
