import { CHAT_LANGUAGES } from './chat-languages';
import { icon } from './icons';
import { languagePicker } from './localization';
import { rosterShell } from './roster-ui';
import { bindingLabel } from './keybindings';
export { icon } from './icons';
export const $ = <T extends HTMLElement = HTMLElement>(id: string) => document.getElementById(id) as T;
const creatorColorParts = [['hair','Hair'],['hairHighlight','Highlights'],['skin','Skin'],['outfit','Outfit'],['accent','Accent'],['head','Head'],['armor','Chest'],['legs','Legs'],['shoes','Boots'],['back','Cloak']];
const creatorCycle = (key:string,label:string) => `<div class="creator-cycle" ${key==='className'?'id="class-options"':''} role="group" aria-labelledby="creator-label-${key}"><span id="creator-label-${key}" class="creator-choice-label">${label}</span><button type="button" data-cycle="${key}" data-step="-1" aria-label="Previous ${label.toLowerCase()}">${icon('left')}</button><output id="${key==='hairStyle'?'hair-style':`creator-value-${key}`}" aria-live="polite"></output><button type="button" data-cycle="${key}" data-step="1" aria-label="Next ${label.toLowerCase()}">${icon('arrow')}</button></div>`;
export function mountUI() {
$('app').innerHTML = `
<div id="play-ui"><main id="game" aria-label="Mossvale game world"><canvas id="world" tabindex="0" aria-label="3D voxel world. Use your configured movement, jump, sprint, interaction and ability keys. Right-click to interact or open player options. Drag to rotate the camera. On touch screens, use the joystick to move, double-tap the world to jump, tap abilities to cast, and pinch to zoom."></canvas></main>
<div class="vignette"></div><div id="labels"></div>
<header class="brand"><img class="brand-art" src="/ui/wordmark.png" alt="Mossvale"/><span class="alpha-badge">ALPHA</span></header>
<div class="realm"><span class="live-dot" id="live-dot"></span><span id="connection">Connecting…</span><span class="realm-divider"></span><span id="population">1 adventurer</span></div>
<section id="waypoint-hud" role="group" aria-label="Waypoint" hidden><span id="waypoint-arrow" aria-hidden="true">${icon('up')}</span><div class="waypoint-copy"><strong id="waypoint-name"></strong><span id="waypoint-distance"></span></div><button id="waypoint-clear" type="button" aria-label="Clear waypoint" title="Clear waypoint">${icon('close')}</button></section>
<div id="unit-frames" hidden></div>
<button id="party-hud" class="party-hud glass" aria-label="Open your party" hidden></button>
<section id="party-invitation" popover="manual" role="dialog" aria-modal="false" aria-labelledby="party-invitation-title" aria-describedby="party-invitation-message">
<h2 id="party-invitation-title">${icon('invite')} Party invitation</h2><p id="party-invitation-message" role="status" aria-live="polite"></p><p id="party-invitation-note" hidden></p>
<div class="party-invitation-actions"><button id="party-invitation-accept" type="button" class="primary-button">Accept</button><button id="party-invitation-decline" type="button" class="primary-button">Decline</button></div>
</section>
<aside class="location" aria-label="Local map"><div id="performance-hud" role="group" aria-label="Game performance" aria-live="off" hidden></div><div class="location-title"><span id="zone-name">THE GREENWOOD</span></div><button id="minimap-button" type="button" aria-describedby="zone-location" data-binding-title="m" data-binding-name="Open world map" aria-label="Open world map"><canvas id="minimap" width="240" height="165" aria-hidden="true"></canvas><span class="map-location" id="zone-location" title="Willow's Rest">Willow's Rest</span><span class="minimap-compass" aria-hidden="true"><svg viewBox="0 0 48 40"><path d="M14 27 34 13M12 14 36 26"/></svg><span class="compass-north">N</span><span class="compass-east">E</span><span class="compass-south">S</span><span class="compass-west">W</span></span><span id="world-time" role="timer" aria-live="off" title="Realm time · One day lasts 40 minutes"></span><kbd aria-hidden="true" data-binding-key="m">M</kbd></button><div class="safe-zone" id="movement-state">The lantern roads</div><div id="pvp-state" role="status" hidden><strong id="pvp-title">SPECTATOR AREA · SAFE</strong><span id="pvp-detail">The sand ring has lethal world PvP. Private matches start at the arena entrance.</span></div></aside>
<button class="quest-tracker" id="quest-button"><span class="eyebrow">${icon('book')} <span id="chapter-label">THE LANTERNS BETWEEN</span></span><strong id="quest-title">A new leaf</strong><span id="quest-summary">Meet Rowan in the town hall</span><span class="quest-line"><i></i><span id="quest-progress">The village keeper is expecting you.</span></span><progress id="quest-meter" max="1" value="0" aria-label="Tracked objective progress" hidden></progress><span id="quest-reward"></span><span class="quest-footer"><span id="quest-state"></span><span id="quest-open">Open journal ›</span></span></button>
<div class="region-intro" id="region-intro"><span>YOU HAVE ARRIVED IN</span><h2 id="zone-intro-title">Willow’s Rest</h2><p id="zone-intro-subtitle">Every great adventure starts somewhere.</p><div>✦</div></div>
<div id="toasts" role="status" aria-live="polite"></div><div id="interact-prompt" class="interact-prompt" hidden><kbd data-binding-key="e">E</kbd><span>Talk to Rowan</span></div>
<section id="target-hud" class="target-hud" aria-label="Current target" hidden><div class="target-heading"><div><strong id="target-name"></strong><span id="target-detail"></span></div><button id="target-action" type="button"></button></div><div id="gather-progress" role="progressbar" aria-label="Gathering progress" aria-valuemin="0" aria-valuemax="100" hidden><span class="gather-track"><span id="gather-fill"></span></span><small id="gather-time"></small></div></section>
<details id="chat-preview" open><summary class="chat-preview-heading" title="Show or hide chat preview">${icon('chat')}<strong>Chat</strong><span id="chat-preview-unread" hidden></span><span class="chat-preview-chevron">${icon('down')}</span></summary><button id="chat-preview-messages" type="button" aria-controls="chat" aria-expanded="false" aria-label="Open chat"></button></details>
<section class="chat" id="chat" aria-label="Chat">
<div class="chat-heading"><div class="chat-tabs" role="tablist" aria-label="Chat channels">${[['world','World'],['system','System'],['whisper','Whispers'],['party','Party']].map(([id,label])=>`<button id="chat-tab-${id}" type="button" role="tab" data-chat-channel="${id}" aria-controls="chat-panel-${id}" aria-selected="${id==='world'}" tabindex="${id==='world'?'0':'-1'}">${label}<span class="chat-unread" hidden aria-hidden="true"></span></button>`).join('')}</div><button id="chat-toggle" type="button" aria-label="Collapse chat" aria-expanded="true" aria-controls="chat-messages" title="Collapse chat"><span id="chat-toggle-label">Hide</span>${icon('down')}</button><button id="chat-close" type="button" aria-label="Close chat and return to game">Back ${icon('close')}</button></div>
<div class="chat-translation-controls"><select id="chat-language" aria-label="Translate with Google" title="Translate with Google. Chat text is sent to Google when enabled." aria-describedby="chat-translation-status"><option value="">Translation off</option>${CHAT_LANGUAGES.map(({code,label})=>`<option value="${code}">${label}</option>`).join('')}</select><a id="chat-translation-attribution" href="https://translate.google.com" target="_blank" rel="noopener noreferrer" hidden><img src="/ui/google-translate-attribution.png" alt="Translated by Google"/></a></div>
<p id="chat-translation-status" role="status" hidden></p>
<div id="chat-messages" class="chat-history">${[['world','World','Say hello to the realm.'],['system','System','Realm notices and rewards appear here.'],['whisper','Whispers','Choose Whisper from a player’s menu or Friends to start a conversation.'],['party','Party','Party messages appear here.']].map(([id,label,empty])=>`<div id="chat-panel-${id}" class="chat-panel" role="tabpanel" aria-labelledby="chat-tab-${id}" ${id==='world'?'':'hidden'}><div id="chat-log-${id}" class="chat-messages" role="log" tabindex="0" aria-label="${label} messages" aria-live="polite" data-empty="${empty}">${id==='system'?'<p class="system-message">Welcome to Mossvale. Make yourself at home.</p>':''}</div></div>`).join('')}</div>
<form id="chat-form"><input id="chat-input" aria-label="World message" maxlength="160" placeholder="Say hello, or /emotes for commands…" title="Emotes: /dance, /laugh, /wave, /cheer, /clap, /bow, /shrug, /cry. /emotes lists commands; /stop stops." autocomplete="off"/><button id="chat-send" aria-label="Send chat message">${icon('arrow')}</button></form>
<button id="chat-resize" type="button" aria-label="Resize chat" title="Drag to resize. Arrow keys adjust size; Home resets."><svg viewBox="0 0 16 16" aria-hidden="true"><path d="M4 3h9v9M3 13 13 3"/></svg></button>
</section>
<div class="bottom-center"><div id="travel-hud" class="travel-hud" role="group" aria-label="Sprint stamina" hidden><div class="stamina-meter"><div><span id="stamina-label">Stamina</span><output id="stamina-value">100</output></div><div id="stamina-track" role="progressbar" aria-label="Sprint stamina" aria-valuemin="0" aria-valuemax="100" aria-valuenow="100"><span id="stamina-fill"></span></div></div><button id="sprint-button" data-key="shift" type="button" data-binding-title="shift" data-binding-name="Hold to sprint" aria-label="Hold to sprint"><span>Sprint</span><kbd data-binding-key="shift">Shift</kbd></button><button id="mount-button" type="button" data-binding-title="h" data-binding-name="Mount or dismount" aria-label="Mount or dismount"><img id="mount-icon" src="/ui/mount-horse.png" alt=""/><span id="mount-label">Level 25</span><kbd data-binding-key="h">H</kbd></button><button id="mounts-button" type="button" aria-label="Choose mount" title="Your mounts"><span class="mount-collection-label">Mounts</span>${icon('down')}</button></div><div class="controls-hint"><span><kbd data-binding-key="w">W</kbd><kbd data-binding-key="a">A</kbd><kbd data-binding-key="s">S</kbd><kbd data-binding-key="d">D</kbd> Move</span><b>·</b><span><kbd data-binding-key=" ">Space</kbd> Jump</span><b>·</b><span>Hotbar abilities</span><b>·</b><button id="hotbar-customize" type="button" data-binding-title="k" data-binding-name="Edit hotbar" aria-label="Edit hotbar">${icon('book')} Edit · <span data-binding-key="k">K</span></button></div><div id="casting-bar" hidden><span id="casting-icon" aria-hidden="true"></span><div class="casting-copy"><div class="casting-caption"><strong id="casting-name"></strong><span id="casting-time" aria-hidden="true"></span></div><div id="casting-progress" role="progressbar" aria-labelledby="casting-name" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span id="casting-fill"></span></div></div></div><div class="hud-action-dock"><div class="hud-xp-rails"><div class="hud-xp-row"><span id="level-label">Lv. 1</span><div class="xp-track" aria-label="Character experience"><span id="xp-fill"></span><span id="xp-label">0 / 100 XP</span></div></div><div class="hud-xp-row hud-job-xp-row"><span id="job-level-label">Job Lv. 1</span><div class="xp-track" aria-label="Job experience"><span id="job-xp-fill"></span><span id="job-xp-label">0 / 100 Job XP</span></div></div></div><div id="hotbar" class="actionbar" role="group" aria-label="Ability hotbar"></div></div></div>
<nav id="game-menus" class="utility glass" aria-label="Game menus"><div id="mobile-menu-heading"><h2 id="mobile-menu-title">Menu</h2><button id="mobile-menu-close" type="button" aria-label="Close menu">${icon('close')}</button></div><button id="inventory-button" data-binding-title="b" data-binding-name="Backpack" aria-label="Backpack">${icon('menu-bags')}<kbd data-binding-key="b">B</kbd></button><button id="journal-button" data-binding-title="j" data-binding-name="Quest board" aria-label="Quest board">${icon('menu-journal')}<kbd data-binding-key="j">J</kbd></button><button id="customize-button" data-binding-title="c" data-binding-name="Character &amp; gear" aria-label="Character &amp; gear">${icon('menu-character')}<kbd data-binding-key="c">C</kbd></button><button id="spells-button" data-binding-title="k" data-binding-name="Combat &amp; professions" aria-label="Combat &amp; professions">${icon('menu-spells')}<kbd data-binding-key="k">K</kbd></button><button id="talents-button" data-binding-title="n" data-binding-name="Skill Tree" aria-label="Skill Tree">${icon('menu-talents')}<kbd data-binding-key="n">N</kbd></button><button id="crafting-button" data-binding-title="f" data-binding-name="Crafting" aria-label="Crafting">${icon('menu-crafting')}<kbd data-binding-key="f">F</kbd></button><button id="arena-button" data-binding-title="u" data-binding-name="Arena" aria-label="Arena">${icon('menu-arena')}<span>Arena</span><kbd data-binding-key="u">U</kbd></button><button id="achievements-button" data-binding-title="y" data-binding-name="Achievements" aria-label="Achievements">${icon('menu-achievements')}<kbd data-binding-key="y">Y</kbd></button><button id="friends-button" data-binding-title="o" data-binding-name="Friends" aria-label="Friends">${icon('menu-friends')}<kbd data-binding-key="o">O</kbd></button><span></span><button id="account-button" aria-label="Account" title="Account">${icon('menu-account')}</button><button id="settings-button" aria-label="Settings and controls" title="Settings &amp; controls">${icon('menu-settings')}</button></nav>
<div class="footer-note"><span id="zone-footer">GREENWOOD</span> · SHARED REALM <span>v0.2</span></div>
<div class="mobile-move" id="mobile-move"><button id="mobile-joystick" type="button" aria-label="Move. Drag the joystick to walk; drag farther to move faster."><span id="mobile-stick" aria-hidden="true"></span><span class="mobile-joystick-label">Move</span></button></div>
<div id="mobile-actions" class="mobile-actions"><button id="mobile-attack" type="button" aria-label="Toggle auto attack" aria-pressed="false">${icon('sword')}<span>Attack</span></button></div>
<div id="mobile-tools" class="mobile-tools" role="group" aria-label="Movement and target actions"><button id="mobile-target" type="button">${icon('bow')}<span>Target</span></button><button id="mobile-interact" type="button">${icon('interact')}<span>Use</span></button><button id="jump-button" type="button">${icon('up')}<span>Jump</span></button><button id="mobile-sprint" type="button" aria-label="Toggle sprint" aria-pressed="false">${icon('route')}<span>Sprint</span></button><button id="mobile-mount" type="button">${icon('travel')}<span>Mount</span></button><button id="mobile-clear" type="button" aria-label="Stop attacking, cancel casting and clear target">${icon('close')}<span>Clear</span></button></div>
<button id="desktop-menu-toggle" type="button" aria-expanded="true" aria-controls="game-menus" aria-label="Hide menus" title="Hide menus"><span>Hide</span>${icon('down')}</button>
<button id="mobile-menu-button" type="button" aria-expanded="false" aria-controls="game-menus">${icon('menu-settings')}<span>Menu</span></button>
<dialog id="panel" class="panel" aria-labelledby="panel-title"><div class="panel-heading"><div><span class="eyebrow" id="panel-eyebrow">YOUR ADVENTURE</span><h2 id="panel-title"></h2></div><button class="close-button" id="close-panel" aria-label="Close panel">${icon('close')}</button></div><div id="panel-content"></div></dialog>
</div>
<dialog id="customizer" class="customizer" aria-labelledby="creator-title">
<form id="character-form" class="creator-form">
<header class="creator-header"><img src="/ui/wordmark.png" alt="Mossvale"/><h1 id="creator-title">Create character</h1><button type="button" id="close-customizer" class="creator-back" aria-label="Back to character selection">${icon('left')} Characters</button><nav id="creator-steps" aria-label="Character creation steps">${['Class','Look','Colors','Name'].map((label,index)=>`<button type="button" id="creator-step-${index}" data-creator-step="${index}" aria-controls="creator-page-${index}" ${index===0?'aria-current="step"':''}><span>${index+1}</span> ${label}</button>`).join('')}</nav></header>
<aside id="creator-selectors" class="creator-controls" aria-label="Character options"><h2 id="creator-step-title" tabindex="-1" autofocus>Choose your class</h2>
<section id="creator-page-0" data-creator-page="0">${creatorCycle('className','Class')}<div class="creator-class-info"><strong id="creator-class-name">Ranger</strong><p id="creator-class-role"></p><p id="class-description" class="class-description"></p><div id="creator-abilities"></div></div></section>
<section id="creator-page-1" data-creator-page="1" hidden>${[['race','Race'],['gender','Gender'],['face','Face'],['hairStyle','Haircut']].map(([key,label])=>creatorCycle(key,label)).join('')}<button id="randomize" type="button" class="creator-shuffle" aria-label="Randomize appearance">${icon('dice')}<span>Shuffle appearance</span></button></section>
<section id="creator-page-2" data-creator-page="2" hidden><label class="creator-color-select" for="creator-color-part">Color to change<select id="creator-color-part">${creatorColorParts.map(([key,label])=>`<option value="${key}">${label}</option>`).join('')}</select></label>
<div id="creator-color-tabs" class="creator-color-tabs" role="tablist" aria-label="Appearance colors">${creatorColorParts.map(([key,label])=>`<button type="button" id="creator-tab-${key}" role="tab" data-color-tab="${key}" aria-controls="color-options" aria-selected="${key==='hair'}" tabindex="${key==='hair'?'0':'-1'}">${label}</button>`).join('')}</div>
<div class="creator-palette-heading"><span id="creator-color-label">Hair color</span><span id="creator-color-value" aria-live="polite"></span></div><div class="creator-custom-color"><label for="creator-custom-color">Choose any color</label><input id="creator-custom-color" type="color" value="#49362b"><button id="creator-reset-dye" type="button" hidden>Use original</button></div><div id="color-options" role="tabpanel" aria-labelledby="creator-tab-hair"></div></section>
<section id="creator-page-3" data-creator-page="3" hidden><p id="creator-summary"></p><div class="creator-name"><label class="field-label" for="character-name">Adventurer name</label><input id="character-name" maxlength="20" minlength="2" required disabled placeholder="Choose a name" autocomplete="off" spellcheck="false" aria-describedby="creation-error"/><p id="creation-error" role="status" aria-live="polite"></p></div><p class="creator-permanent-note">Your name, class and appearance are permanent once created.</p></section></aside>
<div class="customizer-art"><canvas id="character-preview" aria-label="Live preview of your custom voxel character" aria-description="Drag to rotate, or hold a rotation arrow."></canvas><div class="creator-turn-controls"><button id="preview-turn-left" type="button" aria-label="Rotate character left">${icon('left')}</button><span>Drag to rotate</span><button id="preview-turn-right" type="button" aria-label="Rotate character right">${icon('arrow')}</button></div></div>
<footer class="creator-footer"><div class="creator-actions"><button type="button" id="creator-previous" class="creator-back" disabled>${icon('left')} Back</button><button type="button" id="creator-next" class="primary-button">Next ${icon('arrow')}</button><button id="create-character" class="primary-button" type="submit" hidden>Create character ${icon('arrow')}</button></div></footer>
</form></dialog>
${rosterShell()}
<dialog id="character-delete-dialog" class="character-delete-dialog" aria-labelledby="character-delete-title" aria-describedby="character-delete-warning">
<form id="character-delete-form"><h2 id="character-delete-title">Delete character</h2><p>You are deleting <strong id="character-delete-name"></strong>.</p><p id="character-delete-warning">All progress and items for this character will be permanently lost.</p><label for="character-delete-confirmation">Type <strong translate="no">I confirm</strong> to continue</label><input id="character-delete-confirmation" type="text" autocomplete="off" spellcheck="false" autofocus aria-describedby="character-delete-warning character-delete-error"/><p id="character-delete-error" role="alert"></p><div class="character-delete-actions"><button id="character-delete-cancel" type="button">Cancel</button><button id="character-delete-submit" type="submit" disabled>Delete character</button></div></form>
</dialog>
<section id="login" class="login-screen" aria-labelledby="login-title" hidden tabindex="-1">
<div class="login-language">${languagePicker('login-language')}</div>
<canvas id="login-scene" class="login-scene" aria-hidden="true"></canvas>
<img class="login-wordmark" src="/ui/wordmark.png" alt="Mossvale"/>
<div class="login-content"><div class="login-card"><h1 id="login-title">Welcome to Mossvale</h1>
<p id="login-description">Choose your way into the realm.</p>
<p id="login-error" class="login-error" role="alert" hidden></p>
<div class="login-actions"><div id="login-embedded" class="login-embedded" hidden><p id="login-form-status" role="status">Opening secure sign-in…</p><iframe id="login-frame" title="Sign in or create your Mossvale account" referrerpolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-popups-to-escape-sandbox" allow="publickey-credentials-get" hidden></iframe></div><button id="login-provider-cancel" type="button" class="login-register" hidden>Cancel sign-in</button><button id="login-provider-redirect" type="button" class="login-register" hidden>Continue in this tab</button><button id="login-sign-in" type="button" class="primary-button">Sign in with email</button><div id="login-social" class="login-social" role="group" aria-label="Other sign-in methods" hidden><button id="login-google" aria-label="Sign in with Google" type="button" class="social-sign-in" hidden><img src="/ui/sign-in/google.png" alt="" width="360" height="80"></button><button id="login-apple" aria-label="Sign in with Apple" type="button" class="social-sign-in" hidden><img src="/ui/sign-in/apple.png" alt="" width="360" height="80"></button></div><button id="login-wallet" type="button" class="primary-button" hidden>${icon('user')} Sign in with wallet</button><button id="login-register" type="button" class="login-register">Create account</button><button id="login-guest" type="button" class="primary-button" hidden>${icon('compass')} Continue as guest</button><button id="login-retry" type="button" class="primary-button" hidden>${icon('respawn')} Try again</button></div>
<p class="login-social-note" id="login-social-note" hidden>Already play? Use your usual sign-in to keep your characters.</p><p class="login-footnote" id="login-footnote">Your adventure awaits.</p></div></div><nav class="login-service-links" aria-label="Account and help"><a href="/account.html">Your account</a><a href="/support.html">Support</a><a href="/privacy.html">Privacy</a></nav>
</section>
<dialog id="instance-loading" class="loading" aria-labelledby="instance-loading-title" aria-describedby="instance-loading-detail" hidden><img class="loading-wordmark" src="/ui/wordmark.png" alt="Mossvale"/><h2 id="instance-loading-title">Entering the world</h2><p id="instance-loading-detail" role="status">Preparing your surroundings…</p><div class="loading-bar" aria-hidden="true"></div></dialog>
<div id="loading" class="loading" aria-labelledby="startup-loading-title"><img class="loading-wordmark" src="/ui/wordmark.png" alt="Mossvale"/><h2 id="startup-loading-title">Your adventure is taking shape</h2><p id="startup-loading-status" role="status">Preparing the realm…</p><progress id="startup-loading-progress" aria-label="Realm components loaded"></progress><p class="loading-tip"><strong>From your field guide</strong>Tap a quest in your tracker to see its objectives and find where to go next.</p></div>`;
$('instance-loading').addEventListener('cancel',event=>event.preventDefault());
refreshBindingHints();
$('character-list').insertAdjacentHTML('beforebegin',`<div class="roster-language">${languagePicker('roster-language')}</div>`);
$('roster-create').insertAdjacentHTML('afterend','<button type="button" id="roster-delete" class="roster-delete" disabled>Delete character</button>');
}

/** Update existing nodes so changing a binding preserves keyboard focus. */
export function refreshBindingHints(root: ParentNode = document) {
  for (const node of root.querySelectorAll<HTMLElement>('[data-binding-key]')) node.textContent = bindingLabel(node.dataset.bindingKey!);
  for (const node of root.querySelectorAll<HTMLElement>('[data-binding-title]')) {
    const label = bindingLabel(node.dataset.bindingTitle!), name = node.dataset.bindingName!;
    node.title = `${name} · ${label}`;
    node.setAttribute('aria-label', `${name}, ${label}`);
    node.removeAttribute('aria-keyshortcuts');
  }
}
